# Generated by Django 5.0.6 on 2024-06-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('start_time', models.DateTimeField(verbose_name='время старта')),
                ('action', models.CharField(max_length=300, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(verbose_name='приятная привычка')),
                ('is_connected', models.BooleanField(verbose_name='связанная привычка')),
                ('periodicity', models.SmallIntegerField(default=1, verbose_name='периодичность')),
                ('prize', models.CharField(blank=True, max_length=300, null=True, verbose_name='вознаграждение')),
                ('action_time', models.TimeField(verbose_name='время выполнения')),
                ('is_public', models.BooleanField(verbose_name='публичная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
