# Generated by Django 5.0.6 on 2024-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.TimeField(verbose_name='время старта'),
        ),
    ]
