# Generated by Django 5.0.6 on 2024-06-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('start_time',), 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
    ]
