# Generated by Django 5.0.6 on 2024-06-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_action_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_connected',
        ),
    ]
